### ISSUE TITLE
How do I get the picture to scale to the bottom right like in the example?

### ISSUE THREAD

**Issue by GhostTaker40** [rjcarneiro/windows-terminals#13]
![Capture5465416515646545646](https://user-images.githubusercontent.com/42304150/83781847-12744300-a65d-11ea-8716-7755836ded5e.PNG)

**Comment by Dr-Ari-Gami** [comment]
Add:
```
"backgroundImageAlignment": "bottomRight",
"backgroundImageStretchMode": "none",
```

to the bottom of the list.

**Comment by GhostTaker40** [comment]
> Add:
> 
> ```
> "backgroundImageAlignment": "bottomRight",
> "backgroundImageStretchMode": "none",
> ```
> 
> to the bottom of the list.

thanks.

**Comment by rjcarneiro** [comment]
Thanks guys for your help 💪
