### ISSUE TITLE
More Themes

### ISSUE THREAD

**Issue by Darius-Hutchison** [rjcarneiro/windows-terminals#2]

**Comment by rjcarneiro** [comment]
Hi @Darius-Hutchison, thanks for your issue and at the moment I'm working on it. 

Do you have any theme you'll like to share?

**Comment by Darius-Hutchison** [comment]
I was going to add the Detroit Human theme with a pull request, but was beaten to it.

**Comment by rjcarneiro** [comment]
Thanks @Darius-Hutchison for your intentions. Let me know if there's more I can do or if you have more themes to contribute with.
